### ISSUE TITLE
litemall-admin 前端web加载很慢

### ISSUE THREAD

**Issue by fancyfff** [linlinjava/litemall#437]
litemall-admin 首次前端加载很慢，超过一分钟，看了下载的文件，有一个app.js   占用很长时间
该问题能否优化下

**Comment by linlinjava** [comment]
可以有多种方法，你可以研究一下。

当然你可以看看现在演示环境，目前加载速度还可以。
主要的优化方式，就是在litemall-all模块的application.yml文件中使用压缩方式：
```
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
```
